"""adding col in neg

Revision ID: 641c3121e66f
Revises: 9cfbb4bc1c28
Create Date: 2024-01-30 21:32:18.687603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "641c3121e66f"
down_revision: Union[str, None] = "9cfbb4bc1c28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("negotium", sa.Column("deadline", sa.DateTime(), nullable=True))
    op.add_column("negotium", sa.Column("priority", sa.Integer(), nullable=True))
    op.add_column("negotium", sa.Column("completed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("negotium", "completed")
    op.drop_column("negotium", "priority")
    op.drop_column("negotium", "deadline")
    # ### end Alembic commands ###
