"""null fix

Revision ID: c0ec04c11057
Revises: ff9a988a72f7
Create Date: 2024-08-15 19:43:05.463737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0ec04c11057"
down_revision: Union[str, None] = "ff9a988a72f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_negotium_pid", table_name="negotium")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_negotium_pid", "negotium", ["pid"], unique=False)
    op.alter_column("blog_post", "deleted", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
