"""Adding blog post private column

Revision ID: ff9a988a72f7
Revises: 6f5aac6f3d53
Create Date: 2024-07-28 21:00:20.062146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff9a988a72f7"
down_revision: Union[str, None] = "6f5aac6f3d53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_post", sa.Column("private", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_post", "private")
    # ### end Alembic commands ###
